# CircleCI 版本声明
version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:latest

jobs:
  # 编译任务
  build:
    executor: node-executor
    filters:
      branches:
        only: master
    steps:
      # 检出代码
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: node -v
      - run: npm -v
      - run: npm install
      - run: npm run doc:build
  # 部署任务
  deploy:

workflows:
  version: 2
  build-deploy:
    jobs:
      - build

